mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    # /food/
    path('', views.IndexClassView.as_view(), name='index'),
    # /food/1
    path('<int:pk>', views.FoodDetail.as_view(), name='detail'),
    path('item/', views.item, name='item'),
    # /food/add item
    path('add', views.CreateItem.as_view(), name='create_item'),
    # /food/update/id item
    path('update/<int:item_id>', views.update_item, name='update_item'),
    # /food/delete/id
    path('delete/<int:item_id>', views.delete_item, name='delete_item')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('item_name', 'item_desc', 'item_price', 'item_image')

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
# from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

"""
old function based view

def index(request):
    item_list = Item.objects.all()

    template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)
"""

class IndexClassView(ListView):
    # new class based view
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

"""
old function based view 

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    return render(request, 'food/detail.html', context)
"""

class FoodDetail(DetailView):
    # new class based view
    model = Item
    template_name = "food/detail.html"
    

"""
old function based view

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})
"""


class CreateItem(CreateView):
    # class based view
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form, 'item': item})

def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item':item})

mysite/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Welcome {username}, your account is created.")
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

mysite/food/templates/food/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- static files -->
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>MySite</title>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">FoodAPP</a>
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item </a>
            <a href="" class="nav-item nav-link">Delete Item </a>
            <a href="" class="nav-item nav-link">View Item </a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}"> Logout </a>
                <a class="nav-item nav-link" href="{% url 'profile' %}"> Profile </a>
            {% else %}
                <a href="{% url 'login' %}"> Login </a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

mysite/food/templates/food/delete-item.html
{% extends 'food/base.html' %}
{% block body %}

    <form method="POST">
        {% csrf_token %}
        <h2>Are you rure you want to delete {{ item.item_name }} ?</h2>
        <button type="submit" class="btn btn-warning">Confirm</button>
    </form>
{% endblock %}

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img height="300px" src="{{item.item_image}}" class="card" alt="">
            </div>
            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h2>{{ object.item_desc }}</h2>
                <h3>$ {{ object.item_price }}</h3>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>

{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{{ item.item_image }}" alt="" height="120px" width="120px" class="card">
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_dec }}</h5>
                <h6>${{ item.item_price }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body%}
    <form action="" method="POST">
        {% csrf_token %}
        <center><h2>Are you sure you want to delete {{ item.item_name }} ?</h2></center>
        <center><button class="btn btn-danger" type="submit">Confirm deletion</button></center>
    </form>
{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form class="form" action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-info" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/logout.html
{% extends 'food/base.html' %}

{% block body %}
    <h1>You have been logged out</h1>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}
    <h1>{{ user.username }}</h1>
    <img width="100px" height="100px" src="{{ user.profile.image.url }}" alt="">
{% endblock %}

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body%}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-info">Signup</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}